version: '3.1'

services:
    postgres:
        image: postgres:9.6
        environment:
          - POSTGRES_DB=strontium
          - POSTGRES_USER=strontium
          - POSTGRES_PASSWORD=strontium
        volumes:
          - ./.pg_data:/var/lib/postgresql/data
        ports:
          - 5432:5432

    redis:
        image: redis:3.2.10-alpine
        ports:
          - 6379:6379